### ISSUE TITLE
Не работает, почему-то

### ISSUE THREAD

**Issue by nov3o** [HaCk3Dq/vktotg#11]
![screenshot from 2019-02-05 22-24-02](https://user-images.githubusercontent.com/31302079/52298994-6ef61e00-2995-11e9-8df8-df103d639e36.png)
В ВК логинится нормально, но после сообщения о логине в телегу, после некоторого времени ожидания появляется следующее сообщение

**Comment by HaCk3Dq** [comment]
Я погуглил эксепшен: https://stackoverflow.com/a/3172950

Без понятия откуда он, у тебя там в фоне ничего с sql не работает?)

**Comment by nov3o** [comment]
Хз, почему возникла ошибка выше. Возникает "ConnectionError: Connection to Telegram failed 5 times", но это, скорее всего от того, что нет прокси. Закрывай тему

**Comment by nov3o** [comment]
Хз, почему возникла ошибка выше. Возникает "ConnectionError: Connection to Telegram failed 5 times", но это, скорее всего от того, что нет прокси. Проблема у меня
