### ISSUE TITLE
Problem with usability

### ISSUE THREAD

**Issue by IRunLan** [HaCk3Dq/vktotg#9]
Good time. I got this problem (screenshot) when run .py file.
![screenshot](https://user-images.githubusercontent.com/38753431/39300275-d24cb8d8-4953-11e8-932a-9c201dff2096.png)

Also used .exe version, and got the error i cant capture cause its dissapearing too fast, I'm sorry. But it appears after login to telegram, and showing that there is 1 (??? There are 450+ files in my playlist) file to dump.

Anyway, programm creates the channel, and its empty.
![screenshot2](https://user-images.githubusercontent.com/38753431/39300502-9b5f6afe-4954-11e8-9b11-055926c89cf4.png)

And of course, I checked "privacy" settings in VK settings, my playlist is visible to everyone.
Hope, it would help to correct these issues.

**Comment by Valterjherson** [comment]
After thinking couple of hours, I thought that there are any issues with connection.
I changed password, shut down VPN and proxies, rechecked privacy settings and tried again.

Now I got these Errors.

Traceback (most recent call last):
  File "vktotg.py", line 206, in <module>
    if __name__ == '__main__': main()
  File "vktotg.py", line 138, in main
    client = auth_tg()
  File "vktotg.py", line 123, in auth_tg
    client.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\telethon\telegram_bare_client.py", line 204, in connect
    self._sender.connect()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\telethon\network\mtproto_sender.py", line 62, in connect
    self.connection.connect(self.session.server_address, self.session.port)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\telethon\network\connection.py", line 100, in connect
    self.conn.connect(ip, port)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\site-package
s\telethon\extensions\tcp_client.py", line 78, in connect
    self._socket.connect(address)
socket.timeout: timed out

**Comment by HaCk3Dq** [comment]
There isn't any issues with connection in your case. The first error is because the Telethon implementation have been updated and the `.exe` is outdated as well.
I'll update according to the new Telethon specification it in a few days.
